import type { Quality } from '../socioeconomy/model';
export const POLITICAL_ISSUES = ['fiscal_distribution', 'public_services', 'labour_protection', 'income_security', 'infrastructure', 'public_order'] as const;
export type PoliticalIssue = typeof POLITICAL_ISSUES[number];
export const IDEOLOGY_DIMENSIONS = ['fiscal_redistribution', 'market_intervention', 'public_services', 'labour_protection', 'social_progressivism', 'migration_openness', 'national_integration', 'decentralization', 'civil_liberties'] as const;
export type IdeologyDimension = typeof IDEOLOGY_DIMENSIONS[number];
export type ExecutiveSystem = 'presidential' | 'parliamentary' | 'semi_presidential' | 'collective' | 'monarchy_parliamentary' | 'other' | 'unavailable';
export type LegislatureKind = 'unicameral' | 'bicameral' | 'none' | 'unavailable';
export type ElectoralRuleKind = 'proportional' | 'majoritarian' | 'mixed' | 'multi_round' | 'indirect' | 'appointed' | 'other' | 'unavailable';
export type PoliticalCoverage = 'sourced' | 'partial' | 'modelled' | 'modelled_fallback' | 'unavailable' | 'not_applicable';
export interface PoliticalProvenance { status: PoliticalCoverage; referenceDate: string; effectiveDate?: string; retrievedAt: string; source: string; sourceUrl?: string; limitation: string }
export interface IssuePosition { preferenceBps: number; intensityBps: number; confidenceBps: number; materialInterests: string[]; ideologicalPrior: string }
export interface ElectoralRule { kind: ElectoralRuleKind; rounds?: number; status: PoliticalCoverage; provenance: PoliticalProvenance }
export interface LegislativeChamber { id: string; countryId: string; displayName: string; totalSeats?: number; seatsByParty: Record<string, number>; independentOtherSeats?: number; seatAllocationStatus: PoliticalCoverage; electoralRule: ElectoralRule; electionDate?: string; termStart?: string; termEnd?: string; electionProcess: 'current' | 'deferred' | 'unavailable'; provenance: PoliticalProvenance }
export interface GoverningBlocDerivation { sourceText: string; method: 'normalized_source_party_name_substring_v1'; matchedPartyIds: string[]; ambiguous: boolean }
export interface NationalInstitutions { id: string; countryId: string; executiveSystem: ExecutiveSystem; executiveSystemStatus: PoliticalCoverage; executiveSystemProvenance: PoliticalProvenance; legislatureKind: LegislatureKind; chambers: LegislativeChamber[]; governingPartyIds: string[]; governingBlocDerivations: GoverningBlocDerivation[]; confidenceArrangement: 'majority' | 'minority' | 'confidence_and_supply' | 'not_applicable' | 'unavailable'; lastElectionDate?: string; nextElectionDate?: string; electionProcess: 'current' | 'deferred' | 'unavailable'; provenance: PoliticalProvenance }
export interface PartyDimensionMapping { status: 'historical_prior' | 'modelled_neutral'; sourceVariables: string[]; confidenceBps: number; limitation: string }
export interface PartyIdeologicalBasis { status: PoliticalCoverage; method: string; confidenceBps: number; measurementConfidenceBps?: number; temporalApplicabilityConfidenceBps?: number; temporalStatus: 'historical_prior' | 'unavailable'; source?: string; sourceUrl?: string; referenceDate?: string; effectiveDate?: string; sourcePartyIdentity?: { partyFactsId: number; vPartyId: number; vPartyName: string; linkMethod: string }; sourceIdeologicalLabels?: Record<string, { ordinal: number; coderCount: number }>; dimensionMappings?: Record<IdeologyDimension, PartyDimensionMapping>; limitation: string }
export interface PoliticalParty { id: string; countryId: string; displayName: string; fictional: true; provenance: PoliticalProvenance; sourceBasis: { sourcePartyId: string; sourcePartyName: string }; ideology: Record<IdeologyDimension, number>; issuePositions: Record<PoliticalIssue, IssuePosition>; constituencies: string[]; politicalFamily: { status: PoliticalCoverage; value?: string }; ideologicalBasis: PartyIdeologicalBasis; currentSeats: number | null; governmentStatus: 'government' | 'opposition' | 'unavailable' }
export interface PoliticalOrganization { id: string; countryId: string; type: 'union' | 'association'; displayName: string; fictional: true; sourceBasis: { sourceOrganizationId: string; sourceOrganizationName: string }; representedInterests: string[]; representedCohorts: Array<'low' | 'middle' | 'high'>; issuePriorities: PoliticalIssue[]; membership: { status: 'unavailable'; count?: never }; provenance: PoliticalProvenance }
export interface PoliticalRegistryCountry { countryId: string; institutionId: string; partyIds: string[]; organizationIds: string[]; coverage: { institutions: PoliticalCoverage; executiveSystem: PoliticalCoverage; legislature: PoliticalCoverage; electoralSystem: PoliticalCoverage; partyBasis: PoliticalCoverage; partyIdeology: PoliticalCoverage; seats: PoliticalCoverage; coalition: PoliticalCoverage; organizedInterests: PoliticalCoverage; opinionAnchor: PoliticalCoverage } }
export interface PoliticalRegistry { version: 'political-registry-0.13-v4'; referenceDate: string; sourceSnapshotSha256: string; organizedInterestsSourceSha256: string; ideologySourceSnapshotSha256: string; countries: Record<string, PoliticalRegistryCountry>; institutions: Record<string, NationalInstitutions>; parties: Record<string, PoliticalParty>; organizations: Record<string, PoliticalOrganization> }
/** Compact dynamic save tuple: preferences, salience, party support (+ undecided), engagement, sentiment, baseline income, recent issue indexes. */
export type CohortPoliticalOpinion = [number[], number[], number[], number, number, number, number[]];
export const COHORT = Object.freeze({ preferences: 0, salience: 1, support: 2, engagement: 3, sentiment: 4, baselineIncome: 5, drivers: 6 } as const);
export interface RegionalPoliticalOpinion { regionId: string; countryId: string; cohorts: Record<string, CohortPoliticalOpinion> }
export interface PoliticalCountryState { countryId: string; regionIds: string[]; nationalSupportBps: number[]; recentOpinionDrivers: Array<{ date: string; drivers: number[] }> }
/** The four locked organization families. The 0.13 registry supplies parties, unions and
 *  associations; religious organizations have no registry type, so their coverage stays unavailable. */
export type OrganizationFamily = 'party' | 'union' | 'association' | 'religious';
export interface OrganizationPoliticalState { organizationId: string; currentPositions: Record<PoliticalIssue, number>; lastUpdatedOn: string; recentDrivers: Array<{ date: string; issues: PoliticalIssue[] }>; status: 'active' | 'dissolved' | 'banned'; members: Record<string, OrganizationMembership>; fundsUsd?: number; internalCurrents: Record<string, InternalCurrent>; banEvents: OrganizationBanEvent[]; /** Country the organization belongs to (for authority scoping). */ countryId?: string; /** The organization family. Registry unions/associations; parties and dynamic registrations are modelled. */ type?: 'union' | 'association' | 'party'; displayName?: string; /** 'registry' for 0.13-sourced organizations, 'dynamic' for ones created at runtime. */ source?: 'registry' | 'dynamic'; }
export interface OrganizationMembership { personId: string; role: 'member' | 'leader'; joinedOn: string }
export interface InternalCurrent { id: string; name: string; salienceBps: number }
export interface OrganizationBanEvent { date: string; actorPersonId: string; motive: string; evidence: string; appealedOn?: string; appealByPersonId?: string; appealDecision?: 'restore' | 'uphold'; appealResolvedOn?: string }
export interface PoliticalState { version: 'politics-0.13-v1'; registryVersion: 'political-registry-0.13-v4'; initializedOn?: string; lastOpinionUpdate?: string; weeklyEvaluations: number; opinionProvenance?: { status: Quality; method: string; initializedOn: string; limitation: string }; countries: Record<string, PoliticalCountryState>; regionalOpinion: Record<string, RegionalPoliticalOpinion>; organizations: Record<string, OrganizationPoliticalState> }
export const POLITICS_MODEL = Object.freeze({ version: 'politics-0.13-v1' as const, registryVersion: 'political-registry-0.13-v4' as const, schedulerPriority: 400, opinionInertiaBps: 8_000, organizationInertiaBps: 8_000, preferenceInertiaBps: 9_000, salienceInertiaBps: 8_500, sentimentInertiaBps: 8_000, historyLimit: 12, baseEngagementBps: { left: 6_200, centre: 5_500, right: 6_200 }, incomeSensitivityBps: { low: 12_000, middle: 10_000, high: 7_000 }, baseUndecidedBps: { left: 500, centre: 1_000, right: 500 } });
export const emptyPolitics = (): PoliticalState => ({ version: POLITICS_MODEL.version, registryVersion: POLITICS_MODEL.registryVersion, weeklyEvaluations: 0, countries: {}, regionalOpinion: {}, organizations: {} });
