import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const generated = spawnSync(process.execPath, ['scripts/generate-politics-data.mjs', '--check'], { stdio: 'inherit' });
assert.equal(generated.status, 0, 'Generated political registry check failed.');
const registryPath = 'src/data/political-registry.json', sourcePath = 'src/data/source-snapshots/ipu-parline-politics-2026-01-01.json', destination = 'src/data/politics-coverage-report.json';
const registry = JSON.parse(readFileSync(registryPath, 'utf8')), source = JSON.parse(readFileSync(sourcePath, 'utf8'));
assert.equal(registry.sourceSnapshotSha256, createHash('sha256').update(readFileSync(sourcePath)).digest('hex'));
const definitions = Object.values(registry.countries), institutions = Object.values(registry.institutions), chambers = institutions.flatMap(item => item.chambers), parties = Object.values(registry.parties);
for (const chamber of chambers.filter(item => item.seatAllocationStatus === 'sourced')) assert.equal(Object.values(chamber.seatsByParty).reduce((a, b) => a + b, 0) + (chamber.independentOtherSeats ?? 0), chamber.totalSeats, chamber.id);
const fields = ['institutions', 'legislature', 'electoralSystem', 'partyBasis', 'seats', 'coalition', 'organizedInterests', 'opinionAnchor'];
const coverage = Object.fromEntries(fields.map(field => [field, Object.fromEntries(['sourced', 'partial', 'modelled_fallback', 'unavailable', 'not_applicable'].map(status => [status, definitions.filter(item => item.coverage[field] === status).length]))]));
const partyCounts = definitions.map(item => item.partyIds.length), report = { version: 'politics-coverage-0.13-v2', scenarioDate: registry.referenceDate, generatedFrom: { sourceSnapshotSha256: registry.sourceSnapshotSha256, politicalRegistrySha256: createHash('sha256').update(readFileSync(registryPath)).digest('hex') }, methodology: { institutionalSource: `${source.source.publisher}, chambers and latest elections applicable on ${source.referenceDate}`, visiblePartyIdentities: 'Fictional country-specific identities mapped one-to-one to sourced full seat allocations; ideology is deterministic modelled gameplay data.', organizedInterests: 'Unavailable unless sourced; no universal organizations are fabricated.', opinion: 'Nine socioeconomic cohorts per populated region; modelled without polling claims.' }, totals: { countries: definitions.length, sourceCountries: source.countries.length, chambers: chambers.length, chambersWithReconciledSeats: chambers.filter(item => item.seatAllocationStatus === 'sourced').length, representedSeats: chambers.filter(item => item.seatAllocationStatus === 'sourced').reduce((sum, item) => sum + item.totalSeats, 0), fictionalParties: parties.length, fictionalOrganizations: Object.keys(registry.organizations).length, partyCountMin: Math.min(...partyCounts), partyCountMax: Math.max(...partyCounts), distinctPartyCounts: [...new Set(partyCounts)].sort((a, b) => a - b) }, coverage };
assert.deepEqual({ countries: report.totals.countries, sourceCountries: report.totals.sourceCountries, chambers: report.totals.chambers, reconciled: report.totals.chambersWithReconciledSeats }, { countries: 252, sourceCountries: 193, chambers: 281, reconciled: 182 });
const output = `${JSON.stringify(report, null, 2)}\n`; if (process.argv.includes('--write')) writeFileSync(destination, output); else assert.equal(readFileSync(destination, 'utf8'), output, 'Politics coverage report is stale. Run npm run politics:audit:generate.');
console.log(JSON.stringify(report, null, 2));
if (!process.argv.includes('--write')) { const test = spawnSync(process.execPath, ['node_modules/vitest/vitest.mjs', 'run', 'src/simulation/__tests__/politics.test.ts', 'src/simulation/__tests__/politicsWorld.test.ts', '--reporter=verbose'], { stdio: 'inherit' }); process.exit(test.status ?? 1); }
